### PR TITLE
Add README.md

### PR DESCRIPTION
**Pull request by eriknyquist**
First draft of top-level README for CODK-Z

### CODE REVIEW

**Comment by eriknyquist** [comment]
@bigdinotech @calvinatintel @SidLeung @bbaltz505

**Comment by calvinatintel** [comment]
Looks good to me

**Comment by bbaltz505** [comment]
Do we need to explain to the users to source the zephyr-env.sh file or they can take their cue from the error message? As far as i can tell, we can't source the file from withing the makefile.

**Comment by bbaltz505** [comment]
'make clone' step is not needed

**Comment by calvinatintel** [comment]
I think https://github.com/01org/CODK-Z/pull/7 overrides this one

**Comment by eriknyquist** [comment]
yeah, closing

**Pull request closed without merging**
