### PR TITLE
Add 'help' text to Makefile

### PR DESCRIPTION
**Pull request by eriknyquist**
@bbaltz505 @calvinatintel please review

### CODE REVIEW

**Comment by calvinatintel** [comment]
Should it end with `exit 1`?

**Comment by bbaltz505** [comment]
+1

**Comment by bbaltz505** [comment]
I'm ok either way. The help target has to be called explicitly so i don't think anything is looking at the return code in that case (as opposed to a usage check)

**Comment by eriknyquist** [comment]
Actually it's the first target, so it doesn't have to be called explicitly. Calling "make" with no args will do it as well. So maybe in that case it should return 1?

**Comment by bbaltz505** [comment]
that sounds good.

**Comment by eriknyquist** [comment]
Updated in all 3 PRs

**Comment by bbaltz505** [comment]
+1

**Comment by eriknyquist** [comment]
@calvinatintel please merge

**Comment by bbaltz505** [comment]
merged

**Pull request closed without merging**
