### PR TITLE
Include BLE firmware update info in README

### PR DESCRIPTION
**Pull request by calvinatintel**
@abrailex @bbaltz505 @noelpaz @eriknyquist

### CODE REVIEW

**Comment by bbaltz505** [comment]
Should we mention that the board must be manually reset for the programming to start

**Comment by calvinatintel** [comment]
The script prompts the user to reset the board. Do you think we should also write it in readme?

**Comment by bbaltz505** [comment]
Yeah, I like that.
* Note: The script will prompt the user to manually reset the board

**Comment by calvinatintel** [comment]
Updated

**Comment by bbaltz505** [comment]
+1

**Comment by bbaltz505** [comment]
cherry-picked

**Pull request closed without merging**
